[package]
name = "libkrun"
version = "1.8.1"
edition = { workspace = true }
rust-version = { workspace = true }
repository = "https://github.com/containers/libkrun"
license = "Apache-2.0"
publish = false

[build-dependencies]
bindgen = { workspace = true }
